backend:
  name: github
  repo: artnmis/nabadiganta-web # উদাহরণ: abid/nabadiganta-site
  branch: main
  base_url: https://decap-auth-gateway.justalltech1.workers.dev/
  auth_endpoint: auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "initiatives"
    label: "Initiatives"
    folder: "src/content/initiatives"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "notices"
    label: "Notices"
    folder: "src/content/notices"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Notice Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Notice Content", name: "body", widget: "markdown" }